### PR TITLE
Gracefully send a QUIT message when the client closes

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**

### CODE REVIEW

**Comment by prawnsalad** [comment]
We could do with allowing a custom quit message to be set here. How about changing `SendQuitOnClientClose` to be a string, defaulting to an empty string. If it's not empty, then it sends the quit message?

You also need to track if the user has send a quit message already.

**Comment by digitalcircuit** [comment]
@prawnsalad By "defaulting to an empty string", you mean when loading the configuration, correct?

I.e. the example config could still specify the setting by default, with a remark on commenting it out to disable sending a quit on close.  Given several IRC clients send a quit on close, it seems weird to not do this by default in Kiwi IRC when configured according to the example.

**Comment by prawnsalad** [comment]
@digitalcircuit if the config option isn't set, it defaults to an empty string. So for a QUIT message to be sent on close the config option must have a non empty string set.

**Comment by digitalcircuit** [comment]
@prawnsalad Yep, that makes sense.  I mostly meant updating `config.conf.example` to have a value specified by default so people who just copy and modify the config get this working, which @ItsOnlyBinary did with the most recent push.  Thank you, both!

**Pull request merged**
