### PR TITLE
Consolidated channel read loop per client

### PR DESCRIPTION
**Pull request by vith**
1302960 is the main change, the rest were just lint warnings and other small stuff that got in the way of testing with the race detector. Let me know if you want those split out to separate PRs.

Tested with http + https + unix socket listeners all enabled at the same time.

The only races I still get are during config reload.

### CODE REVIEW

**Comment by prawnsalad** [comment]
Probably my lack of understanding, but how does this loop ever exit? It would keep breaking to the label and then entering the loop again?

https://github.com/kiwiirc/webircgateway/blob/e9f4ae25d9d43af24e98b377fa1b846242568d87/pkg/webircgateway/client.go#L584

**Comment by vith** [comment]
Breaking with a label is not like a `goto`; the `for` loop *is* the labeled statement, so the `break` targets that loop. It was used here because a plain `break` would target the `select`.

**Comment by prawnsalad** [comment]
Aha, understood.
So what about the case where a client sends a quit and then closes, then the loop breaks because of this close before throttled messages have managed to be sent upstream?

**Comment by prawnsalad** [comment]
Nvm, gone over it again and looks like I was just confused over.. something.

**Pull request merged**
